"""Which AI runs the headless jobs. config.json "agent": "claude" (default) or "grok".

The job scripts (refresh/chase/voice/people) name tools logically - "slack.read_channel",
"gmail.search_threads" - and call run(prompt, tools). This module maps those names to the
agent's own tool ids and invokes the right CLI.

Grok: Slack is opt-in (config.json "use_slack"). Off, the Slack plugin is not started and
doctor does not probe it. Vercel is never started. Jobs pass --effort low because the Grok
CLI defaults to xhigh. Gmail is the bundled gmail_mcp.py server (not Claude's connector).
"""
import hashlib, json, os, re, shlex, shutil, subprocess, sys
from pathlib import Path

from .paths import ROOT
WIN = sys.platform == "win32"
_GROK_JOB_HOME = ROOT / "state" / "grok-home"

# logical "service.tool" -> per-agent fully-qualified tool id.
# Claude can reach Slack two ways: the Slack *plugin* (plugin:slack:slack, default) or the
# claude.ai Slack *connector*. Same tools, different prefix; the wrong one makes a refresh
# silently find nothing. doctor.py detects which is connected and stores config "slack_source".
# Miro (Roadmap card) is the official Miro plugin; jobs allow the whole server ("miro.*").
_CLAUDE_SLACK = {"plugin": "mcp__plugin_slack_slack__slack_{}", "connector": "mcp__claude_ai_Slack__slack_{}"}
# Miro likewise: the Miro plugin (plugin:miro:miro) or the claude.ai Miro connector. Jobs allow the
# whole server either way; doctor.py stores which one is connected as config "miro_source".
_CLAUDE_MIRO = {"plugin": "mcp__plugin_miro_miro", "connector": "mcp__claude_ai_Miro",
                "server": "mcp__miro"}
# "server" = a user-added HTTP server literally named "miro":
#   claude mcp add --scope user --transport http miro https://mcp.miro.com/
# (--transport http is required: `claude mcp add` defaults to stdio and would try to run the URL.)
_FMT = {
    "claude": {"slack": _CLAUDE_SLACK["plugin"], "gmail": "mcp__claude_ai_Gmail__{}", "miro": _CLAUDE_MIRO["plugin"]},
    "grok":   {"slack": "slack__slack_{}",       "gmail": "gmail__{}",                "miro": "miro"},
}

# Grok CLI defaults to xhigh; Open Loops jobs are unattended JSON, not coding.
_GROK_DISALLOWED = (
    "Agent,run_terminal_cmd,search_replace,read_file,todo_write,write,"
    "grep,list_dir,web_search,web_fetch"
)


def _cfg():
    from .store import load_cfg  # config.json over config.template.json, so "model" has its default
    return load_cfg()


def name():
    return (_cfg().get("agent") or "claude").strip().lower()


def slack_source():
    """Claude only: "plugin" (default) or "connector" - see _CLAUDE_SLACK."""
    v = (_cfg().get("slack_source") or "plugin").strip().lower()
    return v if v in _CLAUDE_SLACK else "plugin"


def miro_source():
    """Claude only: "plugin" (default), "connector" or "server" - see _CLAUDE_MIRO."""
    v = (_cfg().get("miro_source") or "plugin").strip().lower()
    return v if v in _CLAUDE_MIRO else "plugin"


def display_name(agent=None):
    """"Claude" / "Grok" for the selected agent, or for the one named."""
    n = (agent or name()).strip().lower()
    return {"claude": "Claude", "grok": "Grok"}.get(n, n.capitalize())


def cli():
    """Path or command for the agent's CLI (also used to open its sign-in terminal)."""
    if name() == "grok":
        # grok installs to ~/.grok/bin, which Finder/launchd PATHs usually lack
        return shutil.which("grok") or str(Path.home() / ".grok" / "bin" / "grok")
    return "claude"


def use_slack():
    """Grok only: Slack plugin is off unless the user ticks Use Slack in Settings."""
    return bool(_cfg().get("use_slack"))


def slack_enabled():
    """Whether jobs should pass Slack tools. Claude unchanged (still gated on slack_self_id)."""
    return True if name() != "grok" else use_slack()


def grok_job_env():
    """Env for headless Grok: skip Vercel always, skip Slack unless use_slack.

    Grok loads Slack/Vercel from Claude plugins; project .grok/config.toml cannot
    disable those. disabled_mcp_servers in a job-local GROK_HOME does.
    """
    home = _GROK_JOB_HOME
    home.mkdir(parents=True, exist_ok=True)
    src = Path.home() / ".grok"
    for name_ in ("auth.json", "trusted_folders.toml", "trusted_folders.toml.lock"):
        origin, dest = src / name_, home / name_
        if origin.exists() or origin.is_symlink():
            if dest.exists() or dest.is_symlink():
                dest.unlink()
            dest.symlink_to(origin)
    disabled = ["vercel"] if use_slack() else ["vercel", "slack"]
    (home / "config.toml").write_text(
        "# Generated by Open Loops for headless Grok jobs. Do not edit.\n"
        "disabled_mcp_servers = " + json.dumps(disabled) + "\n",
        encoding="utf-8")
    env = dict(os.environ)
    env["GROK_HOME"] = str(home)
    env["GROK_CLAUDE_AGENTS_ENABLED"] = "0"
    env["GROK_CLAUDE_SKILLS_ENABLED"] = "0"
    env["GROK_CURSOR_SKILLS_ENABLED"] = "0"
    env["GROK_CURSOR_AGENTS_ENABLED"] = "0"
    return env


def _qualify(tools):
    fmt = dict(_FMT.get(name()) or _FMT["claude"])
    if name() == "claude":  # from the server actually found, so a renamed server gets its real tool ids
        fmt["slack"] = tool_prefix(server_name("slack")) + "__slack_{}"
        fmt["gmail"] = tool_prefix(server_name("gmail")) + "__{}"
        fmt["miro"] = tool_prefix(server_name("miro"))
    out = []
    for t in tools:
        svc, tool = t.split(".", 1)
        pat = fmt[svc]
        # "miro.*" -> the bare server id: Claude Code reads that as every tool on that server
        out.append(pat.format(tool) if "{}" in pat else pat)
    return list(dict.fromkeys(out))


# Claude setup steps the checklist can start from a button (doctor.py names them in each red row's
# "connect" key, app.py's /api/connect/<step> runs them). The server names are what `claude mcp list`
# prints on Claude Code 2.1.x; doctor.py matches them exactly and falls back to a looser match.
CLAUDE_SERVERS = {
    "slack": {"plugin": "plugin:slack:slack", "connector": "claude.ai Slack"},
    "gmail": {"connector": "claude.ai Gmail"},
    "miro":  {"plugin": "plugin:miro:miro", "connector": "claude.ai Miro", "server": "miro"},
}
CONNECT_STEPS = ("login", "slack_install", "slack", "gmail", "miro")
_MARKETPLACE = "claude-plugins-official"  # where the Slack plugin lives
_MARKETPLACE_SRC = "anthropics/claude-plugins-official"


def _has_marketplace():
    """Whether `claude plugin marketplace list` already knows the official marketplace."""
    try:
        p = subprocess.run(["claude", "plugin", "marketplace", "list"], capture_output=True, text=True,
                           encoding="utf-8", errors="replace", timeout=60, shell=WIN)
        return _MARKETPLACE in (p.stdout or "")
    except Exception:
        return False  # adding it again is harmless; failing to add it breaks the install


def login_cmd(step):
    """The commands for one Claude setup step, run in order -> [argv, ...], or None (unknown step, or not Claude).

    Each opens the browser at most once and needs nothing typed: the user only clicks Allow. `mcp login`
    gets --no-browser off Windows because app.py runs it on a pseudo-terminal, reads the sign-in link it
    prints and opens that itself (the CLI refuses to wait for the browser when stdin is not a terminal).
    On Windows app.py gives it a console window of its own instead, and the CLI opens the browser."""
    if name() != "claude" or step not in CONNECT_STEPS:
        return None
    if step == "login":
        return [["claude", "auth", "login"]]
    if step == "slack_install":
        add = [] if _has_marketplace() else [["claude", "plugin", "marketplace", "add", _MARKETPLACE_SRC]]
        return add + [["claude", "plugin", "install", f"slack@{_MARKETPLACE}"]]
    return [["claude", "mcp", "login", server_name(step)] + ([] if WIN else ["--no-browser"])]


def server_name(svc):
    """The Claude server for "slack" / "gmail" / "miro" on the configured route. doctor.py saves the name
    `claude mcp list` actually printed (config "claude_servers"); that one is used when it is on the same route
    and a plain name (Windows passes it through cmd.exe), else today's usual name. Sign-in and tool ids both
    come from here, so a renamed server is never signed in to while jobs allow tools it does not have."""
    src = {"slack": slack_source, "miro": miro_source}.get(svc, lambda: "connector")()
    seen = str((_cfg().get("claude_servers") or {}).get(svc) or "")
    if seen and re.fullmatch(r"[\w .:@/-]{1,100}", seen) and _route_of(seen, svc) == src:
        return seen
    return CLAUDE_SERVERS[svc][src]


def tool_prefix(server):
    """Claude Code's tool-id prefix for a server: "mcp__" + its name with anything but letters, digits, _ and -
    made _ (plugin:slack:slack -> mcp__plugin_slack_slack, claude.ai Gmail -> mcp__claude_ai_Gmail)."""
    return "mcp__" + re.sub(r"[^A-Za-z0-9_-]", "_", server)


def _route_of(server, svc):
    """"plugin" / "connector" / "server" for a server name, by exact match or by the shape of the name."""
    exact = next((s for s, n in CLAUDE_SERVERS[svc].items() if n == server), None)
    if exact:
        return exact
    low = server.lower()
    return ("plugin" if low.startswith("plugin:") else "connector" if low.startswith("claude.ai") else None) if svc in low else None


# ---- Installing the agent's CLI from the checklist: the "install" setup step (doctor.py offers it on the
# "<AI> is installed" row when the CLI is missing, app.py runs it like the sign-in steps). Every vendor now ships
# a standalone installer script, so no route needs Node, npm or Homebrew: the scripts need only curl + bash on a
# Mac and PowerShell on Windows, which both come with the OS. Checked against the vendors' pages on 2026-09-23:
#   Claude Code  https://code.claude.com/docs/en/setup  (native install, "Recommended"; lands in ~/.local/bin)
#   Codex        https://github.com/openai/codex        (install script; lands in ~/.local/bin, Windows
#                %LOCALAPPDATA%\Programs\OpenAI\Codex\bin). npm i -g @openai/codex and brew install --cask codex
#                also work but need Node or Homebrew first, so they are the manual fallback in INSTALL.md.
#   Grok         https://docs.x.ai/build/overview        (install script; lands in ~/.grok/bin)
# Download first, run second: the script is saved whole to state/install/ and checked non-empty before anything runs,
# so a download cut off half-way never executes (piping curl into bash would run what had arrived so far). Then the
# new CLI must answer `<cli> --version` before the step counts as done. The page shows every command, one per line,
# exactly as they run, so pasting them by hand does the same.
INSTALL_STEP = "install"
_INSTALL = {  # agent -> (Mac/Linux script, what runs it, Windows script, the CLI, where it is documented, who makes it)
    "claude": ("https://claude.ai/install.sh", "bash", "https://claude.ai/install.ps1", "claude",
               "https://code.claude.com/docs/en/setup", "Anthropic"),
    "codex":  ("https://chatgpt.com/codex/install.sh", "sh", "https://chatgpt.com/codex/install.ps1", "codex",
               "https://github.com/openai/codex", "OpenAI"),
    "grok":   ("https://x.ai/cli/install.sh", "bash", "https://x.ai/cli/install.ps1", "grok",
               "https://docs.x.ai/build/overview", "xAI"),
}
_PS = ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass"]


def prereq(win=None):
    """What is on this computer that an install route could use -> {tool: bool}. The installer scripts need only
    curl + bash (Mac/Linux) or PowerShell (Windows); node / npm / brew / winget are reported for the manual routes."""
    win = WIN if win is None else win
    tools = ["powershell", "node", "npm", "winget"] if win else ["curl", "bash", "node", "npm", "brew"]
    return {t: shutil.which(t) is not None for t in tools}


def install_cmd(agent=None, win=None):
    """How to install an agent's CLI (default: the selected one) -> dict, or None for an agent with no known installer:
      "steps"    [(kind, argv), ...] run in order, each only if the one before exited 0. kind is "download", "install"
                 or "check"; app.py names a failure by it. "download" saves the script to "script".
      "command"  what the page shows before the button is pressed, and what to paste by hand: on a Mac every step,
                 joined by && so each runs only if the last worked; on Windows one PowerShell block with the same gates
      "needs"    the tools the steps cannot run without (doctor.py says so, and offers no button, when one is missing)
      "agent", "id"  name exactly what the page showed; app.py refuses a press whose pair no longer matches
      "cli", "script", "source", "vendor"."""
    win = WIN if win is None else win
    who = (agent or name()).strip().lower()
    got = _INSTALL.get(who)
    if not got:
        return None
    url, shell, ps_url, cli_, src, vendor = got
    folder = ROOT / "state" / "install"
    if win:
        script = str(folder / f"{who}-install.ps1")
        pq = lambda x: "'" + str(x).replace("'", "''") + "'"  # PowerShell '...' quoting: a quote is doubled
        # The download fails as a whole (Stop), including an empty file, so a partial or empty script never runs
        get = ["$ErrorActionPreference = 'Stop'",
               f"New-Item -ItemType Directory -Force -Path {pq(folder)} | Out-Null",
               f"Invoke-WebRequest -UseBasicParsing -Uri {pq(ps_url)} -OutFile {pq(script)}",
               f"if ((Get-Item -LiteralPath {pq(script)}).Length -eq 0) {{ throw 'The download was empty.' }}"]
        steps = [("download", _PS + ["-Command", "; ".join(get)]),
                 ("install", _PS + ["-File", script]),
                 ("check", [cli_, "--version"])]
        # Shown (and pasted by hand) as one PowerShell block with the same gates: it stops at the first failure,
        # and throw ends only the block, not the PowerShell window it is pasted into.
        command = "\n".join(["& {"] + ["  " + g for g in get] + [
            f"  powershell -NoProfile -ExecutionPolicy Bypass -File {pq(script)}",
            "  if ($LASTEXITCODE -ne 0) { throw \"The installer stopped with exit code $LASTEXITCODE.\" }",
            f"  {cli_} --version", "}"])
        needs = ["powershell"]
    else:
        script = str(folder / f"{who}-install.sh")
        steps = [("download", ["mkdir", "-p", str(folder)]),
                 ("download", ["curl", "-fsSL", "-o", script, url]),
                 ("download", ["test", "-s", script]),  # an empty 200 is a failed download too
                 ("install", [shell, script]),
                 ("check", [cli_, "--version"])]
        # pasted as is, each runs only if the last worked
        command, needs = " &&\n".join(shlex.join(a) for _, a in steps), ["curl", "bash"]
    return {"steps": steps, "command": command, "needs": needs, "agent": who, "cli": cli_, "script": script,
            "source": src, "vendor": vendor,
            "id": hashlib.sha256((who + "\0" + command).encode("utf-8")).hexdigest()[:16]}


# What the checklist says when an install ends badly, by what went wrong (app.py records which). Plain words as
# #25 asks: what happened, then what to do; no exit codes or file paths. The installer's own output stays in
# state/connect-install.log and the page's Console.
INSTALL_SAID = {
    "download": "{ai}'s installer couldn't download. Check your internet connection and press Install {ai} again.",
    "check":   "{ai} was installed but won't start. Press Install {ai} to try again, or ask IT to install {ai}.",
    "install": "{ai}'s installer stopped with an error. Press Install {ai} to try again. If it fails again, paste the "
               "commands below into Terminal (Windows: PowerShell) and press Enter.",
    "timeout": "The install took longer than 10 minutes, so Open Loops stopped it. Press Install {ai} to try again.",
    "start":   "Open Loops couldn't start {ai}'s installer. Press Install {ai} to try again.",
    "changed": "The AI chosen in Settings changed since this page showed the Install button, so nothing was installed. "
               "Press Check again.",
}


def install_dirs():
    """Where the installer scripts put the CLIs. A Finder-launched app, or a terminal opened before the install, does
    not have them on PATH yet; app.py adds the ones that exist so the re-check and the jobs find the new CLI."""
    home = Path.home()
    dirs = [home / ".local" / "bin", home / ".grok" / "bin"]
    if WIN and os.environ.get("LOCALAPPDATA"):
        dirs.append(Path(os.environ["LOCALAPPDATA"]) / "Programs" / "OpenAI" / "Codex" / "bin")
    return dirs


def model():
    """config.json "model": the Claude model the jobs run on. An alias (sonnet, haiku, opus) or a
    full id. Blank means whatever `claude` defaults to on this machine, which is usually the most
    expensive model the user has - so the template says sonnet: plenty for reading threads and
    writing JSON, at a fraction of the cost. Grok ignores it."""
    return str(_cfg().get("model") or "").strip()


def effort():
    """config.json "effort": low | medium | high | xhigh | max, how hard the model thinks per turn.
    Template: xhigh with sonnet (opus at medium is the other sensible pairing). Blank = CLI default."""
    return str(_cfg().get("effort") or "").strip().lower()


def claude_args(tools):
    args = ["claude", "-p", "--output-format", "text", "--allowedTools", ",".join(_qualify(tools))]
    if model():
        args += ["--model", model()]
    if effort():
        args += ["--effort", effort()]
    return args


def run(prompt, tools):
    """One unattended prompt with only the given MCP tools allowed -> CompletedProcess."""
    if name() == "grok":
        # --cwd matters: .grok/config.toml there defines the bundled Gmail MCP server
        # (gmail_mcp.py, which does its own Google auth via gmail_auth.py).
        args = [cli(), "--cwd", str(ROOT), "-p", prompt, "--verbatim",
                "--output-format", "plain", "--max-turns", "50", "--effort", "low",
                "--disable-web-search", "--no-plan", "--no-subagents", "--no-auto-update",
                "--tools", "search_tool,use_tool",
                "--disallowed-tools", _GROK_DISALLOWED]
        for t in _qualify(tools):
            args += ["--allow", f"MCPTool({t})"]
        return subprocess.run(args, capture_output=True, text=True,
                              encoding="utf-8", errors="replace", env=grok_job_env(), shell=WIN)
    # shell=True only on Windows, to resolve claude.cmd (npm shim) via PATH
    return subprocess.run(claude_args(tools), input=prompt, capture_output=True, text=True,
                          encoding="utf-8", errors="replace", shell=WIN)
